import React from "react";
import { useNavigate } from "react-router-dom";

const GN = "#00ffd1";
const ff = "ui-sans-serif,system-ui,-apple-system,Segoe UI,Roboto,Arial";

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div style={{ marginBottom: 40 }}>
      <h2 style={{ fontSize: 16, fontWeight: 900, color: GN, marginBottom: 12, letterSpacing: ".02em" }}>{title}</h2>
      <div style={{ fontSize: 14, color: "rgba(255,255,255,.72)", lineHeight: 1.85 }}>{children}</div>
    </div>
  );
}

export default function Privacy() {
  const nav = useNavigate();
  return (
    <div style={{ minHeight: "100vh", background: "#050814", color: "white", fontFamily: ff, padding: "60px 24px" }}>
      <div style={{ maxWidth: 760, margin: "0 auto" }}>

        {/* header */}
        <div style={{ marginBottom: 48 }}>
          <button onClick={() => nav(-1)} style={{ display: "flex", alignItems: "center", gap: 8, background: "none", border: "none", color: "rgba(255,255,255,.5)", fontSize: 13, cursor: "pointer", marginBottom: 32, padding: 0 }}>
            ← Back
          </button>
          <div style={{ display: "flex", alignItems: "center", gap: 10, marginBottom: 16 }}>
            <div style={{ width: 28, height: 28, borderRadius: 8, background: `linear-gradient(135deg,${GN},#00b8ff)`, display: "flex", alignItems: "center", justifyContent: "center", fontSize: 14, fontWeight: 900, color: "#050814" }}>A</div>
            <span style={{ fontSize: 14, fontWeight: 900, color: "rgba(255,255,255,.6)" }}>Asymmetric AI</span>
          </div>
          <h1 style={{ fontSize: 32, fontWeight: 950, margin: "0 0 10px", color: "white" }}>Privacy Policy</h1>
          <p style={{ fontSize: 13, color: "rgba(255,255,255,.4)", margin: 0 }}>Last updated: April 2026</p>
        </div>

        <div style={{ height: 1, background: "rgba(255,255,255,.08)", marginBottom: 40 }} />

        <Section title="1. Information We Collect">
          <p style={{ marginBottom: 10 }}>We collect only the minimum information required to operate the platform:</p>
          <ul style={{ paddingLeft: 20, display: "flex", flexDirection: "column", gap: 8 }}>
            <li><strong style={{ color: "white" }}>Email address</strong> — used for account login and notifications</li>
            <li><strong style={{ color: "white" }}>Encrypted API keys</strong> — stored with AES-128 (Fernet) encryption, never in plain text</li>
            <li><strong style={{ color: "white" }}>Trade history</strong> — signals, entry/exit prices, P&L generated by the engine</li>
            <li><strong style={{ color: "white" }}>Session settings</strong> — mode, style, symbol, and configuration preferences</li>
          </ul>
          <p style={{ marginTop: 10 }}>We do not collect your name, phone number, address, or payment information.</p>
        </Section>

        <Section title="2. How We Use Your Information">
          <ul style={{ paddingLeft: 20, display: "flex", flexDirection: "column", gap: 8 }}>
            <li>To operate the AI trading engine on your behalf</li>
            <li>To display your trading history, equity, and performance analytics</li>
            <li>To send account-related notifications (session start/stop, drawdown alerts)</li>
            <li>To maintain platform security and prevent unauthorized access</li>
          </ul>
          <p style={{ marginTop: 10 }}>We do not sell, rent, or share your personal data with third parties for marketing purposes.</p>
        </Section>

        <Section title="3. API Key Security">
          <p style={{ marginBottom: 10 }}>Your exchange API keys are the most sensitive data we handle. We protect them by:</p>
          <ul style={{ paddingLeft: 20, display: "flex", flexDirection: "column", gap: 8 }}>
            <li>Encrypting all API keys with AES-128 (Fernet) symmetric encryption at rest</li>
            <li>Never logging, displaying, or transmitting API keys in plain text</li>
            <li>Only using keys to send trade instructions — never to access account info beyond what is needed</li>
            <li>Storing encrypted keys in a secured database with access controls</li>
          </ul>
        </Section>

        <Section title="4. Data Storage">
          Your data is stored on secured servers. Trade history, equity data, and session logs are retained to provide you with portfolio analytics and performance history. You may request deletion of your account and all associated data at any time by contacting us.
        </Section>

        <Section title="5. Cookies & Tracking">
          We use session cookies to maintain your login state. We do not use third-party tracking cookies, analytics platforms, or advertising pixels. We do not track you across other websites.
        </Section>

        <Section title="6. Data Sharing">
          <p style={{ marginBottom: 10 }}>We do not sell or share your data with third parties except:</p>
          <ul style={{ paddingLeft: 20, display: "flex", flexDirection: "column", gap: 8 }}>
            <li>When required by law or valid legal process</li>
            <li>To your exchange (Binance, Bybit, OKX) — only trade instructions, never personal data</li>
          </ul>
        </Section>

        <Section title="7. Your Rights">
          <ul style={{ paddingLeft: 20, display: "flex", flexDirection: "column", gap: 8 }}>
            <li><strong style={{ color: "white" }}>Access</strong> — You can view all data we hold on you through the dashboard</li>
            <li><strong style={{ color: "white" }}>Deletion</strong> — You can request full account and data deletion at any time</li>
            <li><strong style={{ color: "white" }}>Correction</strong> — You can update your email and settings at any time</li>
            <li><strong style={{ color: "white" }}>Portability</strong> — You can export your trade history from the History page</li>
          </ul>
        </Section>

        <Section title="8. Security">
          We implement reasonable technical and organizational measures to protect your data. However, no system is 100% secure. In the event of a data breach affecting your account, we will notify you promptly via email.
        </Section>

        <Section title="9. Children">
          Asymmetric AI is not intended for users under 18 years of age. We do not knowingly collect personal information from minors.
        </Section>

        <Section title="10. Changes to This Policy">
          We may update this Privacy Policy from time to time. We will notify registered users of material changes via email. Continued use of the Platform after changes constitutes acceptance of the updated policy.
        </Section>

        <Section title="11. Contact">
          For privacy-related requests or questions, contact us at:{" "}
          <a href="mailto:support.asymetricai@gmail.com" style={{ color: GN }}>support.asymetricai@gmail.com</a>
        </Section>

        <div style={{ height: 1, background: "rgba(255,255,255,.08)", marginBottom: 24 }} />
        <p style={{ fontSize: 12, color: "rgba(255,255,255,.25)", lineHeight: 1.7 }}>
          © 2026 Asymmetric AI · asymetricai.com · Demo mode only · No real funds at risk
        </p>
      </div>
    </div>
  );
}
